apiVersion: apps/v1
kind: Deployment
metadata:
  name: authentication-service
  namespace: default
  labels:
    app: authentication-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: authentication-service
  template:
    metadata:
      labels:
        app: authentication-service
    spec:
      containers:
      - name: authentication-service
        image: gcr.io/textchat-0/authentication-service:v20
        ports:
        - containerPort: 3000
        env:
        - name: DB_PW
          valueFrom:
            secretKeyRef:
              name: credentials
              key: password
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: credentials
              key: username
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: credentials
              key: jwt_secret