apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-config-map
data:
  config.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
          http:
    processors:
      batch:
        timeout: 1s
    exporters:
      jaeger:
        endpoint: "jaeger-collector.default.svc.cluster.local:14250"
        tls:
          insecure: true
    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [jaeger]
