apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq
  namespace: default
type: Opaque
data:
  rabbitmq-username: cmFiYml0dXNlcg==
  rabbitmq-password: cmFiYml0cGFzc3dvcmQ=
  rabbitmq-erlangCookie: c2VjcmV0Y29va2ll